/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'linkedin_test';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String GROUP = 'assets/Group.png';
  static const String ETH = 'assets/eth.png';
  static const String KING = 'assets/king.png';
  static const String KINGU = 'assets/kingu.png';
  static const String SETTING = 'assets/setting.png';
  static const String SHARE = 'assets/share.png';
}
