/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String IBMPLEXMONO_BOLD = 'IBMPlexMono-Bold';
  static const String IBMPLEXMONO_LIGHT = 'IBMPlexMono-Light';
  static const String JOSTMED = 'JostMed';
}
